/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as QaDataIntegrityRouteImport } from './routes/qa-data-integrity'
import { Route as QaCalculationsRouteImport } from './routes/qa-calculations'
import { Route as PriceTrendRouteImport } from './routes/price-trend'
import { Route as PriceLogRouteImport } from './routes/price-log'
import { Route as MenuAnalyticsRouteImport } from './routes/menu-analytics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IngredientsRouteImport } from './routes/ingredients'
import { Route as ImpactCascadeRouteImport } from './routes/impact-cascade'
import { Route as DishAnalysisRouteImport } from './routes/dish-analysis'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DishAnalysisIndexRouteImport } from './routes/dish-analysis.index'
import { Route as RecipesIdRouteImport } from './routes/recipes.$id'
import { Route as OnboardingCreateRestaurantRouteImport } from './routes/onboarding.create-restaurant'
import { Route as IngredientsIdRouteImport } from './routes/ingredients.$id'
import { Route as ImpactCascadeBatchIdRouteImport } from './routes/impact-cascade.$batchId'
import { Route as DishAnalysisIdRouteImport } from './routes/dish-analysis.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const QaDataIntegrityRoute = QaDataIntegrityRouteImport.update({
  id: '/qa-data-integrity',
  path: '/qa-data-integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const QaCalculationsRoute = QaCalculationsRouteImport.update({
  id: '/qa-calculations',
  path: '/qa-calculations',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceTrendRoute = PriceTrendRouteImport.update({
  id: '/price-trend',
  path: '/price-trend',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceLogRoute = PriceLogRouteImport.update({
  id: '/price-log',
  path: '/price-log',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuAnalyticsRoute = MenuAnalyticsRouteImport.update({
  id: '/menu-analytics',
  path: '/menu-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsRoute = IngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactCascadeRoute = ImpactCascadeRouteImport.update({
  id: '/impact-cascade',
  path: '/impact-cascade',
  getParentRoute: () => rootRouteImport,
} as any)
const DishAnalysisRoute = DishAnalysisRouteImport.update({
  id: '/dish-analysis',
  path: '/dish-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DishAnalysisIndexRoute = DishAnalysisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DishAnalysisRoute,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecipesRoute,
} as any)
const OnboardingCreateRestaurantRoute =
  OnboardingCreateRestaurantRouteImport.update({
    id: '/onboarding/create-restaurant',
    path: '/onboarding/create-restaurant',
    getParentRoute: () => rootRouteImport,
  } as any)
const IngredientsIdRoute = IngredientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => IngredientsRoute,
} as any)
const ImpactCascadeBatchIdRoute = ImpactCascadeBatchIdRouteImport.update({
  id: '/$batchId',
  path: '/$batchId',
  getParentRoute: () => ImpactCascadeRoute,
} as any)
const DishAnalysisIdRoute = DishAnalysisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DishAnalysisRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/dish-analysis': typeof DishAnalysisRouteWithChildren
  '/impact-cascade': typeof ImpactCascadeRouteWithChildren
  '/ingredients': typeof IngredientsRouteWithChildren
  '/login': typeof LoginRoute
  '/menu-analytics': typeof MenuAnalyticsRoute
  '/price-log': typeof PriceLogRoute
  '/price-trend': typeof PriceTrendRoute
  '/qa-calculations': typeof QaCalculationsRoute
  '/qa-data-integrity': typeof QaDataIntegrityRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dish-analysis/$id': typeof DishAnalysisIdRoute
  '/impact-cascade/$batchId': typeof ImpactCascadeBatchIdRoute
  '/ingredients/$id': typeof IngredientsIdRoute
  '/onboarding/create-restaurant': typeof OnboardingCreateRestaurantRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/dish-analysis/': typeof DishAnalysisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/impact-cascade': typeof ImpactCascadeRouteWithChildren
  '/ingredients': typeof IngredientsRouteWithChildren
  '/login': typeof LoginRoute
  '/menu-analytics': typeof MenuAnalyticsRoute
  '/price-log': typeof PriceLogRoute
  '/price-trend': typeof PriceTrendRoute
  '/qa-calculations': typeof QaCalculationsRoute
  '/qa-data-integrity': typeof QaDataIntegrityRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dish-analysis/$id': typeof DishAnalysisIdRoute
  '/impact-cascade/$batchId': typeof ImpactCascadeBatchIdRoute
  '/ingredients/$id': typeof IngredientsIdRoute
  '/onboarding/create-restaurant': typeof OnboardingCreateRestaurantRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/dish-analysis': typeof DishAnalysisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/dish-analysis': typeof DishAnalysisRouteWithChildren
  '/impact-cascade': typeof ImpactCascadeRouteWithChildren
  '/ingredients': typeof IngredientsRouteWithChildren
  '/login': typeof LoginRoute
  '/menu-analytics': typeof MenuAnalyticsRoute
  '/price-log': typeof PriceLogRoute
  '/price-trend': typeof PriceTrendRoute
  '/qa-calculations': typeof QaCalculationsRoute
  '/qa-data-integrity': typeof QaDataIntegrityRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dish-analysis/$id': typeof DishAnalysisIdRoute
  '/impact-cascade/$batchId': typeof ImpactCascadeBatchIdRoute
  '/ingredients/$id': typeof IngredientsIdRoute
  '/onboarding/create-restaurant': typeof OnboardingCreateRestaurantRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/dish-analysis/': typeof DishAnalysisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/dish-analysis'
    | '/impact-cascade'
    | '/ingredients'
    | '/login'
    | '/menu-analytics'
    | '/price-log'
    | '/price-trend'
    | '/qa-calculations'
    | '/qa-data-integrity'
    | '/recipes'
    | '/settings'
    | '/signup'
    | '/auth/callback'
    | '/dish-analysis/$id'
    | '/impact-cascade/$batchId'
    | '/ingredients/$id'
    | '/onboarding/create-restaurant'
    | '/recipes/$id'
    | '/dish-analysis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/impact-cascade'
    | '/ingredients'
    | '/login'
    | '/menu-analytics'
    | '/price-log'
    | '/price-trend'
    | '/qa-calculations'
    | '/qa-data-integrity'
    | '/recipes'
    | '/settings'
    | '/signup'
    | '/auth/callback'
    | '/dish-analysis/$id'
    | '/impact-cascade/$batchId'
    | '/ingredients/$id'
    | '/onboarding/create-restaurant'
    | '/recipes/$id'
    | '/dish-analysis'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/dish-analysis'
    | '/impact-cascade'
    | '/ingredients'
    | '/login'
    | '/menu-analytics'
    | '/price-log'
    | '/price-trend'
    | '/qa-calculations'
    | '/qa-data-integrity'
    | '/recipes'
    | '/settings'
    | '/signup'
    | '/auth/callback'
    | '/dish-analysis/$id'
    | '/impact-cascade/$batchId'
    | '/ingredients/$id'
    | '/onboarding/create-restaurant'
    | '/recipes/$id'
    | '/dish-analysis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  DashboardRoute: typeof DashboardRoute
  DishAnalysisRoute: typeof DishAnalysisRouteWithChildren
  ImpactCascadeRoute: typeof ImpactCascadeRouteWithChildren
  IngredientsRoute: typeof IngredientsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MenuAnalyticsRoute: typeof MenuAnalyticsRoute
  PriceLogRoute: typeof PriceLogRoute
  PriceTrendRoute: typeof PriceTrendRoute
  QaCalculationsRoute: typeof QaCalculationsRoute
  QaDataIntegrityRoute: typeof QaDataIntegrityRoute
  RecipesRoute: typeof RecipesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  OnboardingCreateRestaurantRoute: typeof OnboardingCreateRestaurantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-data-integrity': {
      id: '/qa-data-integrity'
      path: '/qa-data-integrity'
      fullPath: '/qa-data-integrity'
      preLoaderRoute: typeof QaDataIntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-calculations': {
      id: '/qa-calculations'
      path: '/qa-calculations'
      fullPath: '/qa-calculations'
      preLoaderRoute: typeof QaCalculationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-trend': {
      id: '/price-trend'
      path: '/price-trend'
      fullPath: '/price-trend'
      preLoaderRoute: typeof PriceTrendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-log': {
      id: '/price-log'
      path: '/price-log'
      fullPath: '/price-log'
      preLoaderRoute: typeof PriceLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu-analytics': {
      id: '/menu-analytics'
      path: '/menu-analytics'
      fullPath: '/menu-analytics'
      preLoaderRoute: typeof MenuAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients': {
      id: '/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact-cascade': {
      id: '/impact-cascade'
      path: '/impact-cascade'
      fullPath: '/impact-cascade'
      preLoaderRoute: typeof ImpactCascadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dish-analysis': {
      id: '/dish-analysis'
      path: '/dish-analysis'
      fullPath: '/dish-analysis'
      preLoaderRoute: typeof DishAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dish-analysis/': {
      id: '/dish-analysis/'
      path: '/'
      fullPath: '/dish-analysis/'
      preLoaderRoute: typeof DishAnalysisIndexRouteImport
      parentRoute: typeof DishAnalysisRoute
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/onboarding/create-restaurant': {
      id: '/onboarding/create-restaurant'
      path: '/onboarding/create-restaurant'
      fullPath: '/onboarding/create-restaurant'
      preLoaderRoute: typeof OnboardingCreateRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$id': {
      id: '/ingredients/$id'
      path: '/$id'
      fullPath: '/ingredients/$id'
      preLoaderRoute: typeof IngredientsIdRouteImport
      parentRoute: typeof IngredientsRoute
    }
    '/impact-cascade/$batchId': {
      id: '/impact-cascade/$batchId'
      path: '/$batchId'
      fullPath: '/impact-cascade/$batchId'
      preLoaderRoute: typeof ImpactCascadeBatchIdRouteImport
      parentRoute: typeof ImpactCascadeRoute
    }
    '/dish-analysis/$id': {
      id: '/dish-analysis/$id'
      path: '/$id'
      fullPath: '/dish-analysis/$id'
      preLoaderRoute: typeof DishAnalysisIdRouteImport
      parentRoute: typeof DishAnalysisRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DishAnalysisRouteChildren {
  DishAnalysisIdRoute: typeof DishAnalysisIdRoute
  DishAnalysisIndexRoute: typeof DishAnalysisIndexRoute
}

const DishAnalysisRouteChildren: DishAnalysisRouteChildren = {
  DishAnalysisIdRoute: DishAnalysisIdRoute,
  DishAnalysisIndexRoute: DishAnalysisIndexRoute,
}

const DishAnalysisRouteWithChildren = DishAnalysisRoute._addFileChildren(
  DishAnalysisRouteChildren,
)

interface ImpactCascadeRouteChildren {
  ImpactCascadeBatchIdRoute: typeof ImpactCascadeBatchIdRoute
}

const ImpactCascadeRouteChildren: ImpactCascadeRouteChildren = {
  ImpactCascadeBatchIdRoute: ImpactCascadeBatchIdRoute,
}

const ImpactCascadeRouteWithChildren = ImpactCascadeRoute._addFileChildren(
  ImpactCascadeRouteChildren,
)

interface IngredientsRouteChildren {
  IngredientsIdRoute: typeof IngredientsIdRoute
}

const IngredientsRouteChildren: IngredientsRouteChildren = {
  IngredientsIdRoute: IngredientsIdRoute,
}

const IngredientsRouteWithChildren = IngredientsRoute._addFileChildren(
  IngredientsRouteChildren,
)

interface RecipesRouteChildren {
  RecipesIdRoute: typeof RecipesIdRoute
}

const RecipesRouteChildren: RecipesRouteChildren = {
  RecipesIdRoute: RecipesIdRoute,
}

const RecipesRouteWithChildren =
  RecipesRoute._addFileChildren(RecipesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  DashboardRoute: DashboardRoute,
  DishAnalysisRoute: DishAnalysisRouteWithChildren,
  ImpactCascadeRoute: ImpactCascadeRouteWithChildren,
  IngredientsRoute: IngredientsRouteWithChildren,
  LoginRoute: LoginRoute,
  MenuAnalyticsRoute: MenuAnalyticsRoute,
  PriceLogRoute: PriceLogRoute,
  PriceTrendRoute: PriceTrendRoute,
  QaCalculationsRoute: QaCalculationsRoute,
  QaDataIntegrityRoute: QaDataIntegrityRoute,
  RecipesRoute: RecipesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  OnboardingCreateRestaurantRoute: OnboardingCreateRestaurantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
