/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as QaTransactionalInvitesRouteImport } from './routes/qa-transactional-invites'
import { Route as QaTeamManagementRouteImport } from './routes/qa-team-management'
import { Route as QaSettingsAdminRouteImport } from './routes/qa-settings-admin'
import { Route as QaRecipesRouteImport } from './routes/qa-recipes'
import { Route as QaRecipeImportRouteImport } from './routes/qa-recipe-import'
import { Route as QaPriceTrendRouteImport } from './routes/qa-price-trend'
import { Route as QaPriceLogSnapshotRouteImport } from './routes/qa-price-log-snapshot'
import { Route as QaMvpReadinessRouteImport } from './routes/qa-mvp-readiness'
import { Route as QaMonitoringRouteImport } from './routes/qa-monitoring'
import { Route as QaMenuPriceAuditRouteImport } from './routes/qa-menu-price-audit'
import { Route as QaMenuAnalyticsRouteImport } from './routes/qa-menu-analytics'
import { Route as QaLiveDeploymentRouteImport } from './routes/qa-live-deployment'
import { Route as QaIngredientsRouteImport } from './routes/qa-ingredients'
import { Route as QaImportExportRouteImport } from './routes/qa-import-export'
import { Route as QaImpactCascadeRouteImport } from './routes/qa-impact-cascade'
import { Route as QaGoogleOauthRouteImport } from './routes/qa-google-oauth'
import { Route as QaDishAnalysisRouteImport } from './routes/qa-dish-analysis'
import { Route as QaDataIntegrityRouteImport } from './routes/qa-data-integrity'
import { Route as QaDashboardRouteImport } from './routes/qa-dashboard'
import { Route as QaCalculationsRouteImport } from './routes/qa-calculations'
import { Route as QaBillingRouteImport } from './routes/qa-billing'
import { Route as QaBetaLaunchRouteImport } from './routes/qa-beta-launch'
import { Route as QaAuthRouteImport } from './routes/qa-auth'
import { Route as QaAtomicRpcRouteImport } from './routes/qa-atomic-rpc'
import { Route as QaApplyPriceRouteImport } from './routes/qa-apply-price'
import { Route as QaAlertsRouteImport } from './routes/qa-alerts'
import { Route as PriceTrendRouteImport } from './routes/price-trend'
import { Route as PriceLogRouteImport } from './routes/price-log'
import { Route as MenuAnalyticsRouteImport } from './routes/menu-analytics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IngredientsRouteImport } from './routes/ingredients'
import { Route as ImpactCascadeRouteImport } from './routes/impact-cascade'
import { Route as DishAnalysisRouteImport } from './routes/dish-analysis'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as DishAnalysisIndexRouteImport } from './routes/dish-analysis.index'
import { Route as RecipesIdRouteImport } from './routes/recipes.$id'
import { Route as OnboardingCreateRestaurantRouteImport } from './routes/onboarding.create-restaurant'
import { Route as IngredientsIdRouteImport } from './routes/ingredients.$id'
import { Route as ImpactCascadeBatchIdRouteImport } from './routes/impact-cascade.$batchId'
import { Route as DishAnalysisIdRouteImport } from './routes/dish-analysis.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const QaTransactionalInvitesRoute = QaTransactionalInvitesRouteImport.update({
  id: '/qa-transactional-invites',
  path: '/qa-transactional-invites',
  getParentRoute: () => rootRouteImport,
} as any)
const QaTeamManagementRoute = QaTeamManagementRouteImport.update({
  id: '/qa-team-management',
  path: '/qa-team-management',
  getParentRoute: () => rootRouteImport,
} as any)
const QaSettingsAdminRoute = QaSettingsAdminRouteImport.update({
  id: '/qa-settings-admin',
  path: '/qa-settings-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRecipesRoute = QaRecipesRouteImport.update({
  id: '/qa-recipes',
  path: '/qa-recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRecipeImportRoute = QaRecipeImportRouteImport.update({
  id: '/qa-recipe-import',
  path: '/qa-recipe-import',
  getParentRoute: () => rootRouteImport,
} as any)
const QaPriceTrendRoute = QaPriceTrendRouteImport.update({
  id: '/qa-price-trend',
  path: '/qa-price-trend',
  getParentRoute: () => rootRouteImport,
} as any)
const QaPriceLogSnapshotRoute = QaPriceLogSnapshotRouteImport.update({
  id: '/qa-price-log-snapshot',
  path: '/qa-price-log-snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const QaMvpReadinessRoute = QaMvpReadinessRouteImport.update({
  id: '/qa-mvp-readiness',
  path: '/qa-mvp-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const QaMonitoringRoute = QaMonitoringRouteImport.update({
  id: '/qa-monitoring',
  path: '/qa-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const QaMenuPriceAuditRoute = QaMenuPriceAuditRouteImport.update({
  id: '/qa-menu-price-audit',
  path: '/qa-menu-price-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const QaMenuAnalyticsRoute = QaMenuAnalyticsRouteImport.update({
  id: '/qa-menu-analytics',
  path: '/qa-menu-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const QaLiveDeploymentRoute = QaLiveDeploymentRouteImport.update({
  id: '/qa-live-deployment',
  path: '/qa-live-deployment',
  getParentRoute: () => rootRouteImport,
} as any)
const QaIngredientsRoute = QaIngredientsRouteImport.update({
  id: '/qa-ingredients',
  path: '/qa-ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const QaImportExportRoute = QaImportExportRouteImport.update({
  id: '/qa-import-export',
  path: '/qa-import-export',
  getParentRoute: () => rootRouteImport,
} as any)
const QaImpactCascadeRoute = QaImpactCascadeRouteImport.update({
  id: '/qa-impact-cascade',
  path: '/qa-impact-cascade',
  getParentRoute: () => rootRouteImport,
} as any)
const QaGoogleOauthRoute = QaGoogleOauthRouteImport.update({
  id: '/qa-google-oauth',
  path: '/qa-google-oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const QaDishAnalysisRoute = QaDishAnalysisRouteImport.update({
  id: '/qa-dish-analysis',
  path: '/qa-dish-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const QaDataIntegrityRoute = QaDataIntegrityRouteImport.update({
  id: '/qa-data-integrity',
  path: '/qa-data-integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const QaDashboardRoute = QaDashboardRouteImport.update({
  id: '/qa-dashboard',
  path: '/qa-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const QaCalculationsRoute = QaCalculationsRouteImport.update({
  id: '/qa-calculations',
  path: '/qa-calculations',
  getParentRoute: () => rootRouteImport,
} as any)
const QaBillingRoute = QaBillingRouteImport.update({
  id: '/qa-billing',
  path: '/qa-billing',
  getParentRoute: () => rootRouteImport,
} as any)
const QaBetaLaunchRoute = QaBetaLaunchRouteImport.update({
  id: '/qa-beta-launch',
  path: '/qa-beta-launch',
  getParentRoute: () => rootRouteImport,
} as any)
const QaAuthRoute = QaAuthRouteImport.update({
  id: '/qa-auth',
  path: '/qa-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const QaAtomicRpcRoute = QaAtomicRpcRouteImport.update({
  id: '/qa-atomic-rpc',
  path: '/qa-atomic-rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const QaApplyPriceRoute = QaApplyPriceRouteImport.update({
  id: '/qa-apply-price',
  path: '/qa-apply-price',
  getParentRoute: () => rootRouteImport,
} as any)
const QaAlertsRoute = QaAlertsRouteImport.update({
  id: '/qa-alerts',
  path: '/qa-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceTrendRoute = PriceTrendRouteImport.update({
  id: '/price-trend',
  path: '/price-trend',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceLogRoute = PriceLogRouteImport.update({
  id: '/price-log',
  path: '/price-log',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuAnalyticsRoute = MenuAnalyticsRouteImport.update({
  id: '/menu-analytics',
  path: '/menu-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsRoute = IngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactCascadeRoute = ImpactCascadeRouteImport.update({
  id: '/impact-cascade',
  path: '/impact-cascade',
  getParentRoute: () => rootRouteImport,
} as any)
const DishAnalysisRoute = DishAnalysisRouteImport.update({
  id: '/dish-analysis',
  path: '/dish-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecipesRoute,
} as any)
const DishAnalysisIndexRoute = DishAnalysisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DishAnalysisRoute,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecipesRoute,
} as any)
const OnboardingCreateRestaurantRoute =
  OnboardingCreateRestaurantRouteImport.update({
    id: '/onboarding/create-restaurant',
    path: '/onboarding/create-restaurant',
    getParentRoute: () => rootRouteImport,
  } as any)
const IngredientsIdRoute = IngredientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => IngredientsRoute,
} as any)
const ImpactCascadeBatchIdRoute = ImpactCascadeBatchIdRouteImport.update({
  id: '/$batchId',
  path: '/$batchId',
  getParentRoute: () => ImpactCascadeRoute,
} as any)
const DishAnalysisIdRoute = DishAnalysisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DishAnalysisRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/dish-analysis': typeof DishAnalysisRouteWithChildren
  '/impact-cascade': typeof ImpactCascadeRouteWithChildren
  '/ingredients': typeof IngredientsRouteWithChildren
  '/login': typeof LoginRoute
  '/menu-analytics': typeof MenuAnalyticsRoute
  '/price-log': typeof PriceLogRoute
  '/price-trend': typeof PriceTrendRoute
  '/qa-alerts': typeof QaAlertsRoute
  '/qa-apply-price': typeof QaApplyPriceRoute
  '/qa-atomic-rpc': typeof QaAtomicRpcRoute
  '/qa-auth': typeof QaAuthRoute
  '/qa-beta-launch': typeof QaBetaLaunchRoute
  '/qa-billing': typeof QaBillingRoute
  '/qa-calculations': typeof QaCalculationsRoute
  '/qa-dashboard': typeof QaDashboardRoute
  '/qa-data-integrity': typeof QaDataIntegrityRoute
  '/qa-dish-analysis': typeof QaDishAnalysisRoute
  '/qa-google-oauth': typeof QaGoogleOauthRoute
  '/qa-impact-cascade': typeof QaImpactCascadeRoute
  '/qa-import-export': typeof QaImportExportRoute
  '/qa-ingredients': typeof QaIngredientsRoute
  '/qa-live-deployment': typeof QaLiveDeploymentRoute
  '/qa-menu-analytics': typeof QaMenuAnalyticsRoute
  '/qa-menu-price-audit': typeof QaMenuPriceAuditRoute
  '/qa-monitoring': typeof QaMonitoringRoute
  '/qa-mvp-readiness': typeof QaMvpReadinessRoute
  '/qa-price-log-snapshot': typeof QaPriceLogSnapshotRoute
  '/qa-price-trend': typeof QaPriceTrendRoute
  '/qa-recipe-import': typeof QaRecipeImportRoute
  '/qa-recipes': typeof QaRecipesRoute
  '/qa-settings-admin': typeof QaSettingsAdminRoute
  '/qa-team-management': typeof QaTeamManagementRoute
  '/qa-transactional-invites': typeof QaTransactionalInvitesRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dish-analysis/$id': typeof DishAnalysisIdRoute
  '/impact-cascade/$batchId': typeof ImpactCascadeBatchIdRoute
  '/ingredients/$id': typeof IngredientsIdRoute
  '/onboarding/create-restaurant': typeof OnboardingCreateRestaurantRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/dish-analysis/': typeof DishAnalysisIndexRoute
  '/recipes/': typeof RecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/impact-cascade': typeof ImpactCascadeRouteWithChildren
  '/ingredients': typeof IngredientsRouteWithChildren
  '/login': typeof LoginRoute
  '/menu-analytics': typeof MenuAnalyticsRoute
  '/price-log': typeof PriceLogRoute
  '/price-trend': typeof PriceTrendRoute
  '/qa-alerts': typeof QaAlertsRoute
  '/qa-apply-price': typeof QaApplyPriceRoute
  '/qa-atomic-rpc': typeof QaAtomicRpcRoute
  '/qa-auth': typeof QaAuthRoute
  '/qa-beta-launch': typeof QaBetaLaunchRoute
  '/qa-billing': typeof QaBillingRoute
  '/qa-calculations': typeof QaCalculationsRoute
  '/qa-dashboard': typeof QaDashboardRoute
  '/qa-data-integrity': typeof QaDataIntegrityRoute
  '/qa-dish-analysis': typeof QaDishAnalysisRoute
  '/qa-google-oauth': typeof QaGoogleOauthRoute
  '/qa-impact-cascade': typeof QaImpactCascadeRoute
  '/qa-import-export': typeof QaImportExportRoute
  '/qa-ingredients': typeof QaIngredientsRoute
  '/qa-live-deployment': typeof QaLiveDeploymentRoute
  '/qa-menu-analytics': typeof QaMenuAnalyticsRoute
  '/qa-menu-price-audit': typeof QaMenuPriceAuditRoute
  '/qa-monitoring': typeof QaMonitoringRoute
  '/qa-mvp-readiness': typeof QaMvpReadinessRoute
  '/qa-price-log-snapshot': typeof QaPriceLogSnapshotRoute
  '/qa-price-trend': typeof QaPriceTrendRoute
  '/qa-recipe-import': typeof QaRecipeImportRoute
  '/qa-recipes': typeof QaRecipesRoute
  '/qa-settings-admin': typeof QaSettingsAdminRoute
  '/qa-team-management': typeof QaTeamManagementRoute
  '/qa-transactional-invites': typeof QaTransactionalInvitesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dish-analysis/$id': typeof DishAnalysisIdRoute
  '/impact-cascade/$batchId': typeof ImpactCascadeBatchIdRoute
  '/ingredients/$id': typeof IngredientsIdRoute
  '/onboarding/create-restaurant': typeof OnboardingCreateRestaurantRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/dish-analysis': typeof DishAnalysisIndexRoute
  '/recipes': typeof RecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/dish-analysis': typeof DishAnalysisRouteWithChildren
  '/impact-cascade': typeof ImpactCascadeRouteWithChildren
  '/ingredients': typeof IngredientsRouteWithChildren
  '/login': typeof LoginRoute
  '/menu-analytics': typeof MenuAnalyticsRoute
  '/price-log': typeof PriceLogRoute
  '/price-trend': typeof PriceTrendRoute
  '/qa-alerts': typeof QaAlertsRoute
  '/qa-apply-price': typeof QaApplyPriceRoute
  '/qa-atomic-rpc': typeof QaAtomicRpcRoute
  '/qa-auth': typeof QaAuthRoute
  '/qa-beta-launch': typeof QaBetaLaunchRoute
  '/qa-billing': typeof QaBillingRoute
  '/qa-calculations': typeof QaCalculationsRoute
  '/qa-dashboard': typeof QaDashboardRoute
  '/qa-data-integrity': typeof QaDataIntegrityRoute
  '/qa-dish-analysis': typeof QaDishAnalysisRoute
  '/qa-google-oauth': typeof QaGoogleOauthRoute
  '/qa-impact-cascade': typeof QaImpactCascadeRoute
  '/qa-import-export': typeof QaImportExportRoute
  '/qa-ingredients': typeof QaIngredientsRoute
  '/qa-live-deployment': typeof QaLiveDeploymentRoute
  '/qa-menu-analytics': typeof QaMenuAnalyticsRoute
  '/qa-menu-price-audit': typeof QaMenuPriceAuditRoute
  '/qa-monitoring': typeof QaMonitoringRoute
  '/qa-mvp-readiness': typeof QaMvpReadinessRoute
  '/qa-price-log-snapshot': typeof QaPriceLogSnapshotRoute
  '/qa-price-trend': typeof QaPriceTrendRoute
  '/qa-recipe-import': typeof QaRecipeImportRoute
  '/qa-recipes': typeof QaRecipesRoute
  '/qa-settings-admin': typeof QaSettingsAdminRoute
  '/qa-team-management': typeof QaTeamManagementRoute
  '/qa-transactional-invites': typeof QaTransactionalInvitesRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dish-analysis/$id': typeof DishAnalysisIdRoute
  '/impact-cascade/$batchId': typeof ImpactCascadeBatchIdRoute
  '/ingredients/$id': typeof IngredientsIdRoute
  '/onboarding/create-restaurant': typeof OnboardingCreateRestaurantRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/dish-analysis/': typeof DishAnalysisIndexRoute
  '/recipes/': typeof RecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/alerts'
    | '/dashboard'
    | '/dish-analysis'
    | '/impact-cascade'
    | '/ingredients'
    | '/login'
    | '/menu-analytics'
    | '/price-log'
    | '/price-trend'
    | '/qa-alerts'
    | '/qa-apply-price'
    | '/qa-atomic-rpc'
    | '/qa-auth'
    | '/qa-beta-launch'
    | '/qa-billing'
    | '/qa-calculations'
    | '/qa-dashboard'
    | '/qa-data-integrity'
    | '/qa-dish-analysis'
    | '/qa-google-oauth'
    | '/qa-impact-cascade'
    | '/qa-import-export'
    | '/qa-ingredients'
    | '/qa-live-deployment'
    | '/qa-menu-analytics'
    | '/qa-menu-price-audit'
    | '/qa-monitoring'
    | '/qa-mvp-readiness'
    | '/qa-price-log-snapshot'
    | '/qa-price-trend'
    | '/qa-recipe-import'
    | '/qa-recipes'
    | '/qa-settings-admin'
    | '/qa-team-management'
    | '/qa-transactional-invites'
    | '/recipes'
    | '/settings'
    | '/signup'
    | '/auth/callback'
    | '/dish-analysis/$id'
    | '/impact-cascade/$batchId'
    | '/ingredients/$id'
    | '/onboarding/create-restaurant'
    | '/recipes/$id'
    | '/dish-analysis/'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/alerts'
    | '/dashboard'
    | '/impact-cascade'
    | '/ingredients'
    | '/login'
    | '/menu-analytics'
    | '/price-log'
    | '/price-trend'
    | '/qa-alerts'
    | '/qa-apply-price'
    | '/qa-atomic-rpc'
    | '/qa-auth'
    | '/qa-beta-launch'
    | '/qa-billing'
    | '/qa-calculations'
    | '/qa-dashboard'
    | '/qa-data-integrity'
    | '/qa-dish-analysis'
    | '/qa-google-oauth'
    | '/qa-impact-cascade'
    | '/qa-import-export'
    | '/qa-ingredients'
    | '/qa-live-deployment'
    | '/qa-menu-analytics'
    | '/qa-menu-price-audit'
    | '/qa-monitoring'
    | '/qa-mvp-readiness'
    | '/qa-price-log-snapshot'
    | '/qa-price-trend'
    | '/qa-recipe-import'
    | '/qa-recipes'
    | '/qa-settings-admin'
    | '/qa-team-management'
    | '/qa-transactional-invites'
    | '/settings'
    | '/signup'
    | '/auth/callback'
    | '/dish-analysis/$id'
    | '/impact-cascade/$batchId'
    | '/ingredients/$id'
    | '/onboarding/create-restaurant'
    | '/recipes/$id'
    | '/dish-analysis'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/alerts'
    | '/dashboard'
    | '/dish-analysis'
    | '/impact-cascade'
    | '/ingredients'
    | '/login'
    | '/menu-analytics'
    | '/price-log'
    | '/price-trend'
    | '/qa-alerts'
    | '/qa-apply-price'
    | '/qa-atomic-rpc'
    | '/qa-auth'
    | '/qa-beta-launch'
    | '/qa-billing'
    | '/qa-calculations'
    | '/qa-dashboard'
    | '/qa-data-integrity'
    | '/qa-dish-analysis'
    | '/qa-google-oauth'
    | '/qa-impact-cascade'
    | '/qa-import-export'
    | '/qa-ingredients'
    | '/qa-live-deployment'
    | '/qa-menu-analytics'
    | '/qa-menu-price-audit'
    | '/qa-monitoring'
    | '/qa-mvp-readiness'
    | '/qa-price-log-snapshot'
    | '/qa-price-trend'
    | '/qa-recipe-import'
    | '/qa-recipes'
    | '/qa-settings-admin'
    | '/qa-team-management'
    | '/qa-transactional-invites'
    | '/recipes'
    | '/settings'
    | '/signup'
    | '/auth/callback'
    | '/dish-analysis/$id'
    | '/impact-cascade/$batchId'
    | '/ingredients/$id'
    | '/onboarding/create-restaurant'
    | '/recipes/$id'
    | '/dish-analysis/'
    | '/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AlertsRoute: typeof AlertsRoute
  DashboardRoute: typeof DashboardRoute
  DishAnalysisRoute: typeof DishAnalysisRouteWithChildren
  ImpactCascadeRoute: typeof ImpactCascadeRouteWithChildren
  IngredientsRoute: typeof IngredientsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MenuAnalyticsRoute: typeof MenuAnalyticsRoute
  PriceLogRoute: typeof PriceLogRoute
  PriceTrendRoute: typeof PriceTrendRoute
  QaAlertsRoute: typeof QaAlertsRoute
  QaApplyPriceRoute: typeof QaApplyPriceRoute
  QaAtomicRpcRoute: typeof QaAtomicRpcRoute
  QaAuthRoute: typeof QaAuthRoute
  QaBetaLaunchRoute: typeof QaBetaLaunchRoute
  QaBillingRoute: typeof QaBillingRoute
  QaCalculationsRoute: typeof QaCalculationsRoute
  QaDashboardRoute: typeof QaDashboardRoute
  QaDataIntegrityRoute: typeof QaDataIntegrityRoute
  QaDishAnalysisRoute: typeof QaDishAnalysisRoute
  QaGoogleOauthRoute: typeof QaGoogleOauthRoute
  QaImpactCascadeRoute: typeof QaImpactCascadeRoute
  QaImportExportRoute: typeof QaImportExportRoute
  QaIngredientsRoute: typeof QaIngredientsRoute
  QaLiveDeploymentRoute: typeof QaLiveDeploymentRoute
  QaMenuAnalyticsRoute: typeof QaMenuAnalyticsRoute
  QaMenuPriceAuditRoute: typeof QaMenuPriceAuditRoute
  QaMonitoringRoute: typeof QaMonitoringRoute
  QaMvpReadinessRoute: typeof QaMvpReadinessRoute
  QaPriceLogSnapshotRoute: typeof QaPriceLogSnapshotRoute
  QaPriceTrendRoute: typeof QaPriceTrendRoute
  QaRecipeImportRoute: typeof QaRecipeImportRoute
  QaRecipesRoute: typeof QaRecipesRoute
  QaSettingsAdminRoute: typeof QaSettingsAdminRoute
  QaTeamManagementRoute: typeof QaTeamManagementRoute
  QaTransactionalInvitesRoute: typeof QaTransactionalInvitesRoute
  RecipesRoute: typeof RecipesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  OnboardingCreateRestaurantRoute: typeof OnboardingCreateRestaurantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-transactional-invites': {
      id: '/qa-transactional-invites'
      path: '/qa-transactional-invites'
      fullPath: '/qa-transactional-invites'
      preLoaderRoute: typeof QaTransactionalInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-team-management': {
      id: '/qa-team-management'
      path: '/qa-team-management'
      fullPath: '/qa-team-management'
      preLoaderRoute: typeof QaTeamManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-settings-admin': {
      id: '/qa-settings-admin'
      path: '/qa-settings-admin'
      fullPath: '/qa-settings-admin'
      preLoaderRoute: typeof QaSettingsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-recipes': {
      id: '/qa-recipes'
      path: '/qa-recipes'
      fullPath: '/qa-recipes'
      preLoaderRoute: typeof QaRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-recipe-import': {
      id: '/qa-recipe-import'
      path: '/qa-recipe-import'
      fullPath: '/qa-recipe-import'
      preLoaderRoute: typeof QaRecipeImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-price-trend': {
      id: '/qa-price-trend'
      path: '/qa-price-trend'
      fullPath: '/qa-price-trend'
      preLoaderRoute: typeof QaPriceTrendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-price-log-snapshot': {
      id: '/qa-price-log-snapshot'
      path: '/qa-price-log-snapshot'
      fullPath: '/qa-price-log-snapshot'
      preLoaderRoute: typeof QaPriceLogSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-mvp-readiness': {
      id: '/qa-mvp-readiness'
      path: '/qa-mvp-readiness'
      fullPath: '/qa-mvp-readiness'
      preLoaderRoute: typeof QaMvpReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-monitoring': {
      id: '/qa-monitoring'
      path: '/qa-monitoring'
      fullPath: '/qa-monitoring'
      preLoaderRoute: typeof QaMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-menu-price-audit': {
      id: '/qa-menu-price-audit'
      path: '/qa-menu-price-audit'
      fullPath: '/qa-menu-price-audit'
      preLoaderRoute: typeof QaMenuPriceAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-menu-analytics': {
      id: '/qa-menu-analytics'
      path: '/qa-menu-analytics'
      fullPath: '/qa-menu-analytics'
      preLoaderRoute: typeof QaMenuAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-live-deployment': {
      id: '/qa-live-deployment'
      path: '/qa-live-deployment'
      fullPath: '/qa-live-deployment'
      preLoaderRoute: typeof QaLiveDeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-ingredients': {
      id: '/qa-ingredients'
      path: '/qa-ingredients'
      fullPath: '/qa-ingredients'
      preLoaderRoute: typeof QaIngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-import-export': {
      id: '/qa-import-export'
      path: '/qa-import-export'
      fullPath: '/qa-import-export'
      preLoaderRoute: typeof QaImportExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-impact-cascade': {
      id: '/qa-impact-cascade'
      path: '/qa-impact-cascade'
      fullPath: '/qa-impact-cascade'
      preLoaderRoute: typeof QaImpactCascadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-google-oauth': {
      id: '/qa-google-oauth'
      path: '/qa-google-oauth'
      fullPath: '/qa-google-oauth'
      preLoaderRoute: typeof QaGoogleOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-dish-analysis': {
      id: '/qa-dish-analysis'
      path: '/qa-dish-analysis'
      fullPath: '/qa-dish-analysis'
      preLoaderRoute: typeof QaDishAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-data-integrity': {
      id: '/qa-data-integrity'
      path: '/qa-data-integrity'
      fullPath: '/qa-data-integrity'
      preLoaderRoute: typeof QaDataIntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-dashboard': {
      id: '/qa-dashboard'
      path: '/qa-dashboard'
      fullPath: '/qa-dashboard'
      preLoaderRoute: typeof QaDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-calculations': {
      id: '/qa-calculations'
      path: '/qa-calculations'
      fullPath: '/qa-calculations'
      preLoaderRoute: typeof QaCalculationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-billing': {
      id: '/qa-billing'
      path: '/qa-billing'
      fullPath: '/qa-billing'
      preLoaderRoute: typeof QaBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-beta-launch': {
      id: '/qa-beta-launch'
      path: '/qa-beta-launch'
      fullPath: '/qa-beta-launch'
      preLoaderRoute: typeof QaBetaLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-auth': {
      id: '/qa-auth'
      path: '/qa-auth'
      fullPath: '/qa-auth'
      preLoaderRoute: typeof QaAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-atomic-rpc': {
      id: '/qa-atomic-rpc'
      path: '/qa-atomic-rpc'
      fullPath: '/qa-atomic-rpc'
      preLoaderRoute: typeof QaAtomicRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-apply-price': {
      id: '/qa-apply-price'
      path: '/qa-apply-price'
      fullPath: '/qa-apply-price'
      preLoaderRoute: typeof QaApplyPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-alerts': {
      id: '/qa-alerts'
      path: '/qa-alerts'
      fullPath: '/qa-alerts'
      preLoaderRoute: typeof QaAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-trend': {
      id: '/price-trend'
      path: '/price-trend'
      fullPath: '/price-trend'
      preLoaderRoute: typeof PriceTrendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-log': {
      id: '/price-log'
      path: '/price-log'
      fullPath: '/price-log'
      preLoaderRoute: typeof PriceLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu-analytics': {
      id: '/menu-analytics'
      path: '/menu-analytics'
      fullPath: '/menu-analytics'
      preLoaderRoute: typeof MenuAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients': {
      id: '/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact-cascade': {
      id: '/impact-cascade'
      path: '/impact-cascade'
      fullPath: '/impact-cascade'
      preLoaderRoute: typeof ImpactCascadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dish-analysis': {
      id: '/dish-analysis'
      path: '/dish-analysis'
      fullPath: '/dish-analysis'
      preLoaderRoute: typeof DishAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/dish-analysis/': {
      id: '/dish-analysis/'
      path: '/'
      fullPath: '/dish-analysis/'
      preLoaderRoute: typeof DishAnalysisIndexRouteImport
      parentRoute: typeof DishAnalysisRoute
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/onboarding/create-restaurant': {
      id: '/onboarding/create-restaurant'
      path: '/onboarding/create-restaurant'
      fullPath: '/onboarding/create-restaurant'
      preLoaderRoute: typeof OnboardingCreateRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$id': {
      id: '/ingredients/$id'
      path: '/$id'
      fullPath: '/ingredients/$id'
      preLoaderRoute: typeof IngredientsIdRouteImport
      parentRoute: typeof IngredientsRoute
    }
    '/impact-cascade/$batchId': {
      id: '/impact-cascade/$batchId'
      path: '/$batchId'
      fullPath: '/impact-cascade/$batchId'
      preLoaderRoute: typeof ImpactCascadeBatchIdRouteImport
      parentRoute: typeof ImpactCascadeRoute
    }
    '/dish-analysis/$id': {
      id: '/dish-analysis/$id'
      path: '/$id'
      fullPath: '/dish-analysis/$id'
      preLoaderRoute: typeof DishAnalysisIdRouteImport
      parentRoute: typeof DishAnalysisRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DishAnalysisRouteChildren {
  DishAnalysisIdRoute: typeof DishAnalysisIdRoute
  DishAnalysisIndexRoute: typeof DishAnalysisIndexRoute
}

const DishAnalysisRouteChildren: DishAnalysisRouteChildren = {
  DishAnalysisIdRoute: DishAnalysisIdRoute,
  DishAnalysisIndexRoute: DishAnalysisIndexRoute,
}

const DishAnalysisRouteWithChildren = DishAnalysisRoute._addFileChildren(
  DishAnalysisRouteChildren,
)

interface ImpactCascadeRouteChildren {
  ImpactCascadeBatchIdRoute: typeof ImpactCascadeBatchIdRoute
}

const ImpactCascadeRouteChildren: ImpactCascadeRouteChildren = {
  ImpactCascadeBatchIdRoute: ImpactCascadeBatchIdRoute,
}

const ImpactCascadeRouteWithChildren = ImpactCascadeRoute._addFileChildren(
  ImpactCascadeRouteChildren,
)

interface IngredientsRouteChildren {
  IngredientsIdRoute: typeof IngredientsIdRoute
}

const IngredientsRouteChildren: IngredientsRouteChildren = {
  IngredientsIdRoute: IngredientsIdRoute,
}

const IngredientsRouteWithChildren = IngredientsRoute._addFileChildren(
  IngredientsRouteChildren,
)

interface RecipesRouteChildren {
  RecipesIdRoute: typeof RecipesIdRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
}

const RecipesRouteChildren: RecipesRouteChildren = {
  RecipesIdRoute: RecipesIdRoute,
  RecipesIndexRoute: RecipesIndexRoute,
}

const RecipesRouteWithChildren =
  RecipesRoute._addFileChildren(RecipesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AlertsRoute: AlertsRoute,
  DashboardRoute: DashboardRoute,
  DishAnalysisRoute: DishAnalysisRouteWithChildren,
  ImpactCascadeRoute: ImpactCascadeRouteWithChildren,
  IngredientsRoute: IngredientsRouteWithChildren,
  LoginRoute: LoginRoute,
  MenuAnalyticsRoute: MenuAnalyticsRoute,
  PriceLogRoute: PriceLogRoute,
  PriceTrendRoute: PriceTrendRoute,
  QaAlertsRoute: QaAlertsRoute,
  QaApplyPriceRoute: QaApplyPriceRoute,
  QaAtomicRpcRoute: QaAtomicRpcRoute,
  QaAuthRoute: QaAuthRoute,
  QaBetaLaunchRoute: QaBetaLaunchRoute,
  QaBillingRoute: QaBillingRoute,
  QaCalculationsRoute: QaCalculationsRoute,
  QaDashboardRoute: QaDashboardRoute,
  QaDataIntegrityRoute: QaDataIntegrityRoute,
  QaDishAnalysisRoute: QaDishAnalysisRoute,
  QaGoogleOauthRoute: QaGoogleOauthRoute,
  QaImpactCascadeRoute: QaImpactCascadeRoute,
  QaImportExportRoute: QaImportExportRoute,
  QaIngredientsRoute: QaIngredientsRoute,
  QaLiveDeploymentRoute: QaLiveDeploymentRoute,
  QaMenuAnalyticsRoute: QaMenuAnalyticsRoute,
  QaMenuPriceAuditRoute: QaMenuPriceAuditRoute,
  QaMonitoringRoute: QaMonitoringRoute,
  QaMvpReadinessRoute: QaMvpReadinessRoute,
  QaPriceLogSnapshotRoute: QaPriceLogSnapshotRoute,
  QaPriceTrendRoute: QaPriceTrendRoute,
  QaRecipeImportRoute: QaRecipeImportRoute,
  QaRecipesRoute: QaRecipesRoute,
  QaSettingsAdminRoute: QaSettingsAdminRoute,
  QaTeamManagementRoute: QaTeamManagementRoute,
  QaTransactionalInvitesRoute: QaTransactionalInvitesRoute,
  RecipesRoute: RecipesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  OnboardingCreateRestaurantRoute: OnboardingCreateRestaurantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
